### ISSUE TITLE
New marker for dev app only

### ISSUE THREAD

**Issue by AlexanderWilfing** [Hanslick-Online/hsl-app#57]
Last month, I created a new column in Baserow (in all three tables) called "Überprüft." As the name suggests, if it is checked, I know it is an entry I already double-checked, if it is unchecked, I still need to proof the data. Would it be possible for this mark to be displayed in the **dev app only**, as part of the data displayed when you click on an icon in the reviews themselves. This would make my work easier, as I would not have to jump between the reviews and Baserow when proofing a text to see whether or not I have double-checked any given entity. However, only if this is a pretty easy feature and does not take a lot of time on your end. Thanks!

**Comment by linxOD** [comment]
actually adding a verification status is not a bad idea. In TEI there is an attribute @cert which refers to the certainty of the data. In combination with @resp which refers to a person or several. e.g. resp="#awilfinger" which means this person is responsible fo the certainty value. 

I added this to the indexes:
`<place cert="high" resp="awilfinger">` 
if you checked the "ueberprueft" checkbox. Otherwise:
`<place cert="medium" resp="awilfinger">` 

The website will show: "Überprüft: mehrfach" if certi=high and "Überprüft: einmalig" if cert=medium

**Comment by AlexanderWilfing** [comment]
I am currently working with the new status for the first time and it is working splendidly. Could you please change the @resp to "#awilfing" instead of "#awilfinger", otherwise the issue could be closed.

**Comment by linxOD** [comment]
will be solved with the next build

**Comment by AlexanderWilfing** [comment]
The new status works perfectly with persons and works, however, places are still shown as "einmalig" even though I already checked them (and included the corresponding marker). Could you take a look prior to release (late July, probably, so no rush)?

**Comment by linxOD** [comment]
fixed with next build

**Comment by AlexanderWilfing** [comment]
Thanks for this as well!
